### ISSUE TITLE
camelCase problem in pubmed

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/octochemdb#112]
Seems a little bit random which fields are in camelCase

![image](https://github.com/cheminfo/octochemdb/assets/1484241/ca2b5680-1097-420b-88ac-1dd6c618fa22)

You should use a library to make this conversion: https://www.npmjs.com/package/camelcase

Please ensure than ISSN -> issn

**Comment by RicardoSilvestr** [comment]
Done
