### ISSUE TITLE
Create sync function for bioassays

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/octochemdb#45]

**Comment by RicardoSilvestr** [comment]
PubChem taxonomy has a "Tested Compounds" section (see 1), which means that somehow a correlation between CID-Taxonomy-Activity exists.
Looking at the structure of bioassay file used in syncBioassays for the same organism in 1 we obtain: 
```
 {
  AID: 245030,
  'BioAssay Name': 'Minimum inhibitory concentration against Penicillium chrysogenum',
  'Deposit Date': 20100524,
  'Modify Date	': 20200703,
  'Source Name': 'ChEMBL',
  'Source ID': ' CHEMBL831447',
  'Substance Type': 'small-molecule',
  'Outcome Type': ' ',
  'Project Category': 'Literature Extracted',
  'BioAssay Group': ' PMID: 15686916',
  'BioAssay Types': ' ',
  'Protein Accessions': ' ',
  'UniProts IDs': ' ',
  'Gene IDs': ' ',
  'Target TaxIDs': ' ',
  'Taxonomy IDs': 5076,
}
```
This means syncBioassays should extract this informations too and that an aggregation between bioassays and taxonomies collections should be created

1: https://pubchem.ncbi.nlm.nih.gov/taxonomy/5076#section=Related-Taxonomies

**Comment by RicardoSilvestr** [comment]
Done
