### ISSUE TITLE
Improve login system

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/octochemdb#46]
https://github.com/cheminfo/docker-pubchem/blob/6aec9044583753207c07776782476fb7ec486201/pubchem/src/utils/Debug.js#L37-L42

**Comment by RicardoSilvestr** [comment]
message logs are stored in admin collection under property "logs" : [{epoch, event}}, if the logs length reach 49 (50 elements) the first element (oldest event)  is removed using shift and the new event is pushed.
