### ISSUE TITLE
More information about naturalProdcut

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/octochemdb#58]
During aggregation we can have the information that it is a naturalProduct but we have nothing else.

For example:

```
db.activesOrNaturals.find({_id:"fncib@LTe[rmF@DYHieDeECdmDeQeVttuLuT@D@@@"})
```

We need at least links to get more information and I don't know how to get them. Need to discuss about this.

**Comment by RicardoSilvestr** [comment]
Integrating this feature would increase the complexity for the user, the copy button of smiles suggested in issue https://github.com/cheminfo/octochemdb/issues/74 would be a better approach.
