### ISSUE TITLE
Many errors during importation

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/octochemdb#64]
import_1   | 2022-08-10T07:34:34.531Z firstSubstanceImport BSON field 'createIndexes.indexes' is the wrong type 'object', expected type 'array'
import_1   | 2022-08-10T07:34:34.532Z syncSubstanceFolder Synchronize full substance folder
import_1   | 2022-08-10T07:34:34.532Z syncSubstanceFolder Synchronize incremental substance folder
import_1   | 2022-08-10T07:34:35.251Z syncSubstanceFolder Processing week: 2022-07-10/
import_1   | 2022-08-10T07:34:35.765Z getFile Downloaded from: Start Import till Substance_087000001_087500000.sdf.gz
import_1   | 2022-08-10T07:34:45.947Z getFile Downloaded from: Substance_087000001_087500000.sdf.gz till Substance_408500001_409000000.sdf.gz
import_1   | 2022-08-10T07:34:56.095Z getFile Downloaded from: Substance_408500001_409000000.sdf.gz till Substance_433000001_433500000.sdf.gz
import_1   | 2022-08-10T07:35:08.362Z getFile Downloaded from: Substance_433000001_433500000.sdf.gz till Substance_465500001_466000000.sdf.gz
import_1   | 2022-08-10T07:35:08.365Z getFile ERROR downloading: https://ftp.ncbi.nlm.nih.gov/pubchem/Substance/Weekly//2022-07-10/SDF//Substance_466000001_466500000.sdf.gz
import_1   | 2022-08-10T07:35:08.365Z syncSubstanceFolder fetch failed
import_1   | 2022-08-10T07:35:08.367Z incrementalSubstanceImport Should never happens.
import_1   | 2022-08-10T07:35:08.367Z cron Closing connection
import_1   | /git/pubchem/node_modules/mongodb/lib/operations/execute_operation.js:20
import_1   |                 return callback(new error_1.MongoNotConnectedError('Client must be connected before running operations'));
import_1   |                                 ^
import_1   | 
import_1   | MongoNotConnectedError: Client must be connected before running operations
import_1   |     at /git/pubchem/node_modules/mongodb/lib/operations/execute_operation.js:20:33
import_1   |     at maybePromise (/git/pubchem/node_modules/mongodb/lib/utils.js:411:5)
import_1   |     at executeOperation (/git/pubchem/node_modules/mongodb/lib/operations/execute_operation.js:16:37)
import_1   |     at Collection.replaceOne (/git/pubchem/node_modules/mongodb/lib/collection.js:175:57)
import_1   |     at PubChemConnection.setProgress (file:///git/pubchem/src/utils/PubChemConnection.js:77:20)
import_1   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
import_1   |     at async logInDB (file:///git/pubchem/src/utils/Debug.js:66:3) {
import_1   |   [Symbol(errorLabels)]: Set(0) {}
import_1   | }
import_1   | 
import_1   | Node.js v18.6.0
import_1   | npm notice 
import_1   | npm notice New minor version of npm available! 8.13.2 -> 8.16.0
import_1   | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.16.0>
import_1   | npm notice Run `npm install -g npm@8.16.0` to update!
import_1   | npm notice

**Comment by RicardoSilvestr** [comment]
```
import_1 | 2022-08-10T07:34:34.531Z firstSubstanceImport BSON field 'createIndexes.indexes' is the wrong type 'object', expected type 'array'
``` 
This error was due to the createindexes() function introduced last week, sometimes i forgot to add the [ ] in the function I already solved it.

```
import_1 | 2022-08-10T07:35:08.365Z getFile ERROR downloading:
https://ftp.ncbi.nlm.nih.gov/pubchem/Substance/Weekly//2022-07-10/SDF//Substance_466000001_466500000.sdf.gz

```

This error happens because the weekly update of 2022-07-10 does not exists anymore, the oldest weekly update for substance is 2022-07-17.
